### ISSUE TITLE
composer error

### ISSUE THREAD

**Issue by alex-granovskiy** [ctidigital/magento2-configurator#75]
Problem 1
    - firegento/fastsimpleimport 1.1.0 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.1.11) does not satisfy that requirement.
    - ctidigital/magento2-configurator 1.3.0 requires firegento/fastsimpleimport 1.1.0 -> satisfiable by firegento/fastsimpleimport[1.1.0].
    - Installation request for ctidigital/magento2-configurator ^1.3 -> satisfiable by ctidigital/magento2-configurator[1.3.0].

**Comment by lucasvm** [comment]
Im getting the same error, is there any updates on this?

**Comment by paulpartington-cti** [comment]
It's not totally ready yet but you can try the 2.2-alpha branch which works with 7.1 
https://github.com/ctidigital/magento2-configurator/tree/2.2-alpha

**Comment by husseycoding** [comment]
Any ideas on timescale for the stable release of this new version?  I'm getting conflict errors for symfony/console[v2.8.40] with the alpha release under M2.2.4 and PHP 7.1.17.  Would you expect that to be working?

**Comment by paulpartington-cti** [comment]
@husseycoding Not too sure yet. There's some errors on the Travis build that I've not figured out yet.

I am running it on 2.2.4 with PHP 7.1.17 though without issues so far.

Might be unrelated but my composer.json has this in as well:

`"minimum-stability": "dev",
    "prefer-stable": true,`

**Comment by husseycoding** [comment]
I feel like I must be missing something here as I can't see how the extension can currently be installed at all with composer:

`composer require ctidigital/magento2-configurator:dev-2.2-alpha`
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove symfony/console v2.8.40
    - Conclusion: don't install symfony/console v2.8.40
    - symfony/yaml 3.4.x-dev conflicts with symfony/console[v2.8.40].
    - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.40].
    - symfony/yaml v3.4.0-BETA1 conflicts with symfony/console[v2.8.40].
    - symfony/yaml v3.4.0-BETA2 conflicts with symfony/console[v2.8.40].
    - symfony/yaml v3.4.0-BETA3 conflicts with symfony/console[v2.8.40].
    - symfony/yaml v3.4.0-BETA4 conflicts with symfony/console[v2.8.40].
    - symfony/yaml v3.4.0-RC1 conflicts with symfony/console[v2.8.40].
    - symfony/yaml v3.4.0-RC2 conflicts with symfony/console[v2.8.40].
    - symfony/yaml v3.4.1 conflicts with symfony/console[v2.8.40].
    - symfony/yaml v3.4.10 conflicts with symfony/console[v2.8.40].
    ...
    (and so on for more versions)
```
`composer why symfony/console`
````
composer/composer                  1.4.1    requires  symfony/console (^2.7 || ^3.0)          
friendsofphp/php-cs-fixer          v2.2.19  requires  symfony/console (^2.4 || ^3.0 || ^4.0)  
magento/composer                   1.2.0    requires  symfony/console (~2.3, !=2.7.0)         
magento/framework                  101.0.4  requires  symfony/console (~2.3, !=2.7.0)         
magento/magento2-base              2.2.4    requires  symfony/console (~2.3, !=2.7.0)         
magento/product-community-edition  2.2.4    requires  symfony/console (~2.3, !=2.7.0)         
sebastian/phpcpd                   2.0.4    requires  symfony/console (~2.7|^3.0)             
sjparkinson/static-review          4.1.1    requires  symfony/console (~2.0)
````
So the highest version of `symfony/console` which can be installed to satisfy this is 2.8.40 being the last version before 3.x (and this version is installed).

Looking on packagist `ctidigital/magento2-configurator` requires `symfony/yaml: >2.8.0` so the earliest version of `symfony/yaml` which could be installed is `2.8.1`
`composer require symfony/yaml:2.8.1`
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - symfony/yaml v2.8.1 conflicts with symfony/dependency-injection[v3.4.10].
    - symfony/yaml v2.8.1 conflicts with symfony/dependency-injection[v3.4.10].
    - symfony/yaml v2.8.1 conflicts with symfony/dependency-injection[v3.4.10].
    - Installation request for symfony/yaml 2.8.1 -> satisfiable by symfony/yaml[v2.8.1].
    - Installation request for symfony/dependency-injection (locked at v3.4.10) -> satisfiable by symfony/dependency-injection[v3.4.10].
```
`composer why symfony/dependency-injection`
```
pdepend/pdepend  2.5.2  requires  symfony/dependency-injection (^2.3.0|^3|^4)
```
`composer why pdepend/pdepend`
```
magento/project-community-edition  2.2.4  requires (for development)  pdepend/pdepend (2.5.2)  
phpmd/phpmd                        2.6.0  requires                    pdepend/pdepend (^2.5)
```
This pretty much carries on - I haven't followed it all the way down, but basically dependencies can't currently be met in order to install `ctidigital/magento2-configurator`.  This is with a clean install of Magento 2.2.4 and clean version of PHP 7.1.17 with alll extensions installed as listed on the spec.

Perhaps you could share the composer.json you are working from which allows you to install the alpha version?

**Comment by paulpartington-cti** [comment]
@husseycoding Thanks for the feedback. I’m away for a few days but I’ll try and take a look some point next week. 

I may also have ran it with ‘—ignore-platform-reqs’ and that might have got round the issue.

**Comment by husseycoding** [comment]
No worries @paulpartington-cti I'll keep an eye on the thread next week.

**Comment by rafashkembi** [comment]
I have opened an issue that may be related to this.
https://github.com/ctidigital/magento2-configurator/issues/83

**Comment by chevli** [comment]
This one is a tricky one as Magento 2.2 is using a very old version of ```symfony/console``` which also includes very old dependencies causing an incompatibility with ```symfony/yaml``` required by configurator.
In order to get the Travis CI builds working correctly I have had to also specify versions for the following packages:
```
composer require symfony/config:4.1.*
composer require symfony/dependency-injection:3.3.*
```
This appeared to allow Magento 2.2 and M2 Configurator v2.X to install.

Magento 2.3 appears to be coming with a newer version of ```symfony/console``` so I am hoping this issue should not occur.

I will close this issue for now although I do appreciate this is merely a workaround.
